use springsecurity;

#select * from loginmaster ;
/*
drop table LOGINMASTER;

CREATE TABLE LOGINMASTER (
USERID  INT PRIMARY KEY,
USERNAME VARCHAR(100) NOT NULL UNIQUE,
PASSWORD VARCHAR(15) NOT NULL ,
USERSTATUS tinyint NOT NULL
);


CREATE TABLE USER_ROLES(
ROLEID INT  NOT NULL,
USERID INT NOT NULL,
AUTHORITY VARCHAR(100) NOT NULL,

CONSTRAINT fk_userID FOREIGN KEY (USERID) REFERENCES LOGINMASTER(USERID)
);

*/

#INSERT INTO LOGINMASTER VALUES(1,'spring','spring',1);

#INSERT INTO USER_ROLES VALUES(1,1,'ROLE_USER');

#SELECT * FROM LOGINMASTER;
#SELECT * FROM USER_ROLES;


#SELECT USERNAME ,PASSWORD ,USERSTATUS FROM LOGINMASTER WHERE USERNAME=?;

#SELECT LM.USERNAME,UR.AUTHORITY FROM LOGINMASTER LM ,USER_ROLES UR WHERE LM.USERID=UR.USERID AND LM.USERNAME=?





#SELECT USERNAME ,PASSWORD ,USERSTATUS FROM LOGINMASTER;

# WHERE USERNAME=?" authorities-by-username-query="

#SELECT LM.USERNAME,UR.AUTHORITY FROM LOGINMASTER LM ,USER_ROLES UR WHERE LM.USERID=UR.USERID AND LM.USERNAME="spring";

/*
drop table USER_ROLES;
drop table LOGINMASTER;
*/
/*

CREATE TABLE user (
USERID  INT PRIMARY KEY auto_increment,
USERNAME VARCHAR(100) NOT NULL UNIQUE,
PASSWORD VARCHAR(100) NOT NULL ,
FIRSTNAME VARCHAR(50) NOT NULL ,
LASTNAME VARCHAR(50),
ADDRESS VARCHAR(250),
CONTACTNU VARCHAR(25),
ACTIVE boolean,  # by default 1 
LASTLOGINDT DATETIME,
SUPERVISOR INT 
);


CREATE TABLE user_role(
id int not null,
roleid INT  NOT NULL,
user_id INT NOT NULL,

CONSTRAINT fk_userID FOREIGN KEY (user_id) REFERENCES user(USERID)
);

department
project
location 
userdeactivation 
user-supervisor mapping

CREATE TABLE roles(
  id int(20) NOT NULL,
  name VARCHAR(15) DEFAULT NULL,
  PRIMARY KEY (id)
  
)




#desc LOGINMASTER;

#insert into loginmaster(USERNAME,PASSWORD,FIRSTNAME,LASTNAME,ADDRESS,CONTACTNU,EMAILID,DEPARTMENT,PROJECT,LOCATION,ACTIVE,LASTLOGINDT,SUPERVISOR) 
#VALUES('spring','spring','Lokesh','LastName','Address','987654321','lokesg@gmail.com',1,1,1,1,now(),1);
*/

#SELECT USERNAME ,PASSWORD ,ACTIVE FROM LOGINMASTER WHERE ACTIVE=1 and USERNAME='spring';

#SELECT LM.USERNAME,UR.AUTHORITY FROM LOGINMASTER LM ,USER_ROLES UR WHERE LM.USERID=UR.USERID AND LM.USERNAME='spring'
insert into roles (name) values("ROLE_ADMIN");
insert into roles (name) values("ROLE_USER");


select * from roles;
select * from user_role;
select * from user;

insert into user_role (user_id,roleid) values(1,1);
insert into user_role (user_id,roleid) values(2,2);


use springsecurity;
#select * from role;
#insert into user(USERNAME,PASSWORD,FIRSTNAME,LASTNAME,ADDRESS,CONTACTNU,EMAILID,DEPARTMENT,PROJECT,LOCATION,ACTIVE,LASTLOGINDT,SUPERVISOR) 
#VALUES('john','21232f297a57a5a743894a0e4a801fc3','John','LastName','Address','987654321','john@gmail.com',1,1,1,1,now(),1);

insert into user(USERNAME,PASSWORD,FIRSTNAME,LASTNAME,ADDRESS,CONTACTNU,EMAILID,DEPARTMENT,PROJECT,LOCATION,ACTIVE,LASTLOGINDT,SUPERVISOR) 
#VALUES('jane','ee11cbb19052e40b07aac0ca060c23ee','Jane','LastName','Address','987654321','jane@gmail.com',1,1,1,1,now(),1);




